apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - protocol: TCP
      port: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - containerPort: 21