apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: http
      protocol: TCP
      port: 21
    - name: pasv
      protocol: TCP
      port: 40000
    - name: list
      protocol: TCP
      port: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 40000
        - containerPort: 20