apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftps
      protocol: TCP
      port: 21
    - name: pasv
      protocol: TCP
      port: 21000
    - name: pasv1
      protocol: TCP
      port: 21001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        env:
          - name: IDB_NAME
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-name
          - name: IDB_USER
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-user
          - name: IDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-password
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ps -o comm | grep "vsftpd" && ps -o comm | grep "telegraf"
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 21000
          name: pasv
        - containerPort: 21001
          name: pasv1