apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql_img
        imagePullPolicy: Never
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-id
                key: name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-id
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-id
                key: password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-id
                key: host
          - name: IDB_NAME
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-name
          - name: IDB_USER
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-user
          - name: IDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-password
        livenessProbe:
          exec:
            command:
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 3306