apiVersion: v1
kind: PersistantVolumeClaim
metadata:
    name: mysql-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: v1
kind: PersistantVolume
metadata:
    name: mysql-pv
spec:
    accessModes:
        -ReadWriteOnce
    resources:
        requests:
            storage: 1Gi