apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_img
        imagePullPolicy: Never
        env:
          - name: IDB_NAME
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-name
          - name: IDB_USER
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-user
          - name: IDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-password
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ps -o comm | grep "telegraf" && ps -o comm "nginx"
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 80
        - containerPort: 443