apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_img
        imagePullPolicy: Never
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-id
                key: host
          - name: IDB_NAME
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-name
          - name: IDB_USER
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-user
          - name: IDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-password
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - rc-service nginx status && rc-service php-fpm7 status
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 5000