apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: https
      protocol: TCP
      port: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_img
        imagePullPolicy: Never
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-id
                key: name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-id
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-id
                key: password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-id
                key: host
          - name: IDB_NAME
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-name
          - name: IDB_USER
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-user
          - name: IDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-id
                key: idb-password
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ps -o comm | grep "telegraf" && ps -o comm | grep "nginx" && ps -o comm | grep "php-fpm7"
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 5050