FROM  alpine:3.13

#install php & mysql?
#https://wiki.alpinelinux.org/wiki/WordPress
RUN  cd /var/www && wget http://wordpress.org/latest.tar.gz && tar -xzvf latest.tar.gz && rm latest.tar.gz

EXPOSE 5050